version: '3.9'

services:
  api:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    volumes:
      - ./app:/code/app
      - ./env:/code/env

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:80
    environment:
      # - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=S2Xqf6PJ5zNjMjBd3x

  db:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=S2Xqf6PJ5zNjMjBd3x
    # volumes: 
    #   - ./db/:/docker-entrypoint-initdb.d
    ports:
      - "3336:3306"